PUT http://localhost:3003/api/blogs/5fcd2d7b9acd401d0e936ea3
Content-Type: application/json

{
    "title":"The Hitchhiker's Guide to the Galaxy",
    "author":"Douglas Adams",
    "url": "www.test.com",
    "likes": 42
}